### ISSUE TITLE
[Problem] UI: Task panel partially cut off

### ISSUE THREAD

**Issue by hkienle** [Ondsel-Development/FreeCAD#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This is what I get: The task panel is partially cut off.
![image](https://github.com/Ondsel-Development/FreeCAD/assets/17142458/7bfa0657-e14b-4001-b84b-ce07398ce4a1)

It's not a show stopper but pretty annoying to work with. Resizing Ondsel Lens / Property view by dragging left or right does not help.

[I am "testing the waters" with my first 2 issue. Is Ondsel interested in these kind of reports or is this the wrong place?]

### Full version info

```shell
OS: PureOS 10 (Byzantium) (GNOME/gnome-xorg)
Word size of Ondsel: 64-bit
Version: 2024.1.0.35631 (Git) AppImage
Build type: Release
Branch: flavor
Hash: badd90ef6d13904890e30a8d8170c8620c7e5a76
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * OpenDark 2023.12.17
  * Ondsel-Lens 2024.1.22.01
```
```


### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sliptonic** [comment]
This is a known issue.  Some work is being done in upstream freecad to fix it.
If you mouse over the very top of the task panel, you can grab and stretch it left.  The entire left edge should be live but isn't, just the top bar.  
The problem will be resolved in upstream so I'm closing the issue here.
See also: https://github.com/FreeCAD/FreeCAD/issues/11016
